language: ruby
bundler_args: --without development
script: "bundle exec rake travis"
rvm:
  - 1.9.3
gemfile:
  - Gemfile
notifications:
  recipients:
    - jeremy.n.friesen@gmail.com
branches:
  only:
    - master